### ISSUE TITLE
ARM64 (Silicon Mac) support

### ISSUE THREAD

**Issue by wookayin** [jackaudio/jack2#685] opened 2020-12-18 23:45 UTC
Hello!

It'd be great jack2 can support arm64 architecture (M1 mac) as well as x86_64, as jack2 serves a dependency to some downstream audio processing applications.

There would be a lot of implementation challenges regarding the architecture difference; for example the codebase uses CAS (compare-and-swap) operation which is not supported by arm64 architecture. This is one of the first errors one would encounter when trying to build JACK2 on arm64 machines.

```
../common/JackAtomicState.h:168:23: error: use of undeclared identifier 'CAS'
            } while (!CAS(Counter(old_val), Counter(new_val), (UInt32*)&fCounter));
                      ^
../common/JackAtomicState.h:184:23: error: use of undeclared identifier 'CAS'
            } while (!CAS(Counter(old_val), Counter(new_val), (UInt32*)&fCounter));
                      ^
6 errors generated.

Waf: Leaving directory `/private/tmp/jack-20201218-88528-awxy3p/jack2-1.9.16/build'
```

Any plans for supporting the new architecture? Thanks!

**Comment by falkTX** [comment] 2020-12-19 12:06
The required dependencies build in universal mode now except one.

I did test this and current jack2 release is working on the M1, just in the emulated mode. Intel 64bit binary clients still work with this.
I want to do a new jack2 release by january 15, it should include universal builds for macOS.

**Comment by falkTX** [comment] 2020-12-26 17:54
Note that although this builds now, it is not very good news in the end..
jack2 built against latest macOS SDK is not able to talk to coreaudio anymore, not even the x64 arch variant.
we can still start the server in dummy backend and connect to it, so the server stuff still works.
sadly an arm64 client cannot talk to a x64 server, and vice-versa.

I have this working on linux, where a x64 server can have clients from many architectures (x86 and even arm through qemu-user stuff)

**Comment by falkTX** [comment] 2020-12-26 17:58
For the curious ones, this is the error when running in arm64 native mode:
```
% jackd -dcoreaudio -dBuiltInSpeakerDevice -r48000 -p256 -P                  
...
Error calling OpenAComponent
Cannot initialize driver
JackServer::Open failed with -1
Failed to open server
```

and the error for x64 rosetta mode:
```
% arch -arch x86_64 jackd -dcoreaudio -dBuiltInSpeakerDevice -r48000 -p256 -P
...
Cannot initialize AUHAL unit
Cannot initialize driver
JackServer::Open failed with -1
Failed to open server
```

contributions and ideas are very welcome.

for building aften on macOS, see https://github.com/DISTRHO/PawPaw/commit/0ea2ad087bb0f7b2542ae5566518cadaeb51004d

**Comment by robertchin** [comment] 2020-12-27 11:34
> For the curious ones, this is the error when running in arm64 native mode:
> 
> ```
> % jackd -dcoreaudio -dBuiltInSpeakerDevice -r48000 -p256 -P                  
> ...
> Error calling OpenAComponent
> Cannot initialize driver
> JackServer::Open failed with -1
> Failed to open server
> ```
> 
> and the error for x64 rosetta mode:
> 
> ```
> % arch -arch x86_64 jackd -dcoreaudio -dBuiltInSpeakerDevice -r48000 -p256 -P
> ...
> Cannot initialize AUHAL unit
> Cannot initialize driver
> JackServer::Open failed with -1
> Failed to open server
> ```
> 
> contributions and ideas are very welcome.
> 
> for building aften on macOS, see [DISTRHO/PawPaw@0ea2ad0](https://github.com/DISTRHO/PawPaw/commit/0ea2ad087bb0f7b2542ae5566518cadaeb51004d)

FYI after should compile natively, you can use homebrew or just grab the patch from https://github.com/Homebrew/homebrew-core/pull/66725

Also for CAS you could adopt std::atomic which would then negate the need for any platform specific CAS code. Specifically std::atomic expresses memory ordering, which is important on ARM since data updates across cores are weakly ordered.

**Comment by falkTX** [comment] 2020-12-27 12:22
> FYI after should compile natively, you can use homebrew or just grab the patch from [Homebrew/homebrew-core#66725](https://github.com/Homebrew/homebrew-core/pull/66725)

Pure native build is not what I am after, but universal build (arm64 + x64). There are a lot of projects that assume that only one architecture will be built at a time, which is 99% the case yes.
So my hacky patch forces the SSE2 mode, which is useful when running as x64, while still work for arm64 within the same binary.

> Also for CAS you could adopt std::atomic which would then negate the need for any platform specific CAS code. Specifically std::atomic expresses memory ordering, which is important on ARM since data updates across cores are weakly ordered.

contributions welcome :)

jack has been running with that same code on linux ARM/aarch64 and users have not reported errors in there. so maybe the issue is just theoretical?

**Comment by robertchin** [comment] 2020-12-27 18:12
I didn't see the linux arm atomic code in linux/JackAtomic_os.h, so I can't comment on what it is doing.

I did try to convert the code a few days ago to std::atomic, but I couldn't test it due to the error you noted above.
https://github.com/robertchin/jack2/commit/815531735f847e617e84f1d5e6cae34a579e6d06

**Comment by falkTX** [comment] 2020-12-27 18:22
> I didn't see the linux arm atomic code in linux/JackAtomic_os.h, so I can't comment on what it is doing.

There is no ARM-specific code there, the fallback is the same I put here for macOS.

Not being able to initialize the AU component jack uses for audio is very weird. The same codebase works if built using an earlier macOS version, then running on that same machine.
That is, the current 1.9.16 osx installer runs on macOS 11 and M1, but obviously it can only support intel-64bit clients.

I still have to deal with Qt5 build on the M1, which I got running for Carla but need to clean up the patches.
A universal build of Qt5 and Qjackctl is necessary, as processes started by intel-64bit binaries on the M1 end up being intel-64bit too. So we need a universal build of Qjackctl to be able to start the arm64 jackd version.

**Comment by falkTX** [comment] 2020-12-27 18:23
> I did try to convert the code a few days ago to std::atomic, but I couldn't test it due to the error you noted above.
> [robertchin@8155317](https://github.com/robertchin/jack2/commit/815531735f847e617e84f1d5e6cae34a579e6d06)

and oh, yes, this is very useful. there is no reason to convert from `struct` to `class` (they are exactly the same in C++ besides the default visibility of private vs public). the rest seems quite useful.
though something to check out later, as the most important part now is getting the coreaudio backend to work.

**Comment by robertchin** [comment] 2020-12-27 19:30
I did the conversion to a class in order to detect all of the uses of the member data, if you'll notice I changes the visibility to private and changes the macros into instance methods. Of course they are non virtual so it is still POD if it matters. 

I can also look into the core audio issue when I have a chance, although I am not too familiar with the jack codebase (I do however have a lot of experience with core audio.)

**Comment by robertchin** [comment] 2020-12-27 19:33
Actually upon re-reading your comment about it working when building on an older OS, the binary might be missing an entitlement for microphone access.

**Comment by falkTX** [comment] 2020-12-27 19:34
> I did the conversion to a class in order to detect all of the uses of the member data, if you'll notice I changes the visibility to private and changes the macros into instance methods. Of course they are non virtual so it is still POD if it matters.

all fine, though for an official commit/PR the class would go back to a struct again. for testing, this is fine.

**Comment by falkTX** [comment] 2020-12-27 19:35
> Actually upon re-reading your comment about it working when building on an older OS, the binary might be missing an entitlement for microphone access.

But this fails when running on the terminal, where the old binary works fine.
I dont know much about this "entitlement" thing now, care to explain?

**Comment by falkTX** [comment] 2020-12-27 19:41
Also, note that where I am testing (a mac-mini M1) does not have an internal microphone, you can see in the jackd CLI args above that I specified only the speakers and playback-only mode on top.

**Comment by robertchin** [comment] 2020-12-28 06:29
Hi, I was wrong. The actual issue turned out to be much simpler -- the compiler switch for the current platform was incorrect, and so it was taking an older deprecated component manager codepath rather than the current new one. Likely on macOS 11 these deprecated APIs were turned into hard failure if they were compiled on or after macOS 11.

Please see the PR https://github.com/jackaudio/jack2/pull/692

**Comment by falkTX** [comment] 2020-12-28 20:44
Thanks a lot, I can confirm that jackd starts now.

And I got some news on the arm64/x64 binary compatibility issue. It seems all due to x86 and x64 using packed structs, while arm64 does not.
So we need to make the `POST_PACKED_STRUCTURE` work on mac arm64.
See common/jack/systemdeps.h for the definition, we can take out the `__aarch64__` part, then just need to figure out how to make that work...

**Comment by robertchin** [comment] 2020-12-28 20:54
Ah, possibly related to Mac arm64 struct alignment differences then -- if I remember correctly, chars are actually a single byte.

**Comment by falkTX** [comment] 2020-12-28 21:02
ok the culprit seems to be `struct _jack_shm_info` in `jack2/common/shm.h`

**Comment by falkTX** [comment] 2020-12-28 21:13
Alright, x86_64 + arm64 interoperability fixed in 94a59faae9bab10089a503b05e2ad878eb209fbd.
The next step is getting Qt5 and Qjackctl in universal build mode.
Coming soon.

**Comment by falkTX** [comment] 2020-12-28 21:15
btw, the situation is:
1. arm64 jackd can talk to arm64 and x86_64 clients
2. x86_64 jackd can only talk to x86_64 clients
 
arm64 clients get a "invalid argument" when trying to map into shared memory created by a x86_64

**Comment by robertchin** [comment] 2020-12-28 22:30
If you don't find a solution first I can take a look tonight in ten hours or so. Actually it would be useful to have a release that compiles and runs without the UI if getting that working is a lot of time, since I am actually trying to get OBS Studio working natively (which is why I submitted patches to aften in homebrew).

**Comment by falkTX** [comment] 2020-12-29 06:48
Oh, it is not a whole lot of effort, I already have a working Qt5 for Carla, just need to make a diff of the changes I needed for the build, and apply that to jack2's build.
Next release is scheduled for January 15 btw. The universal build is not possible to do in CI, so I will run it through my machine.

I can post here a working macos universal jack2 build if you want. just the jack core, no qjackctl yet.

**Comment by robertchin** [comment] 2020-12-29 11:03
I did take a look for quite some time, but I am unfortunately not really sure what is wrong at this point. But I will continue looking...

**Comment by falkTX** [comment] 2020-12-29 11:35
looking for what?

anyway, jack2 works on arm64 now, here is a local build from my system (requires macos 11/bigsur).

[jack2-osx-1.9.16.pkg.zip](https://github.com/jackaudio/jack2/files/5750515/jack2-osx-1.9.16.pkg.zip)
(includes only jack, not qjackctl)

so actually, as arm64 builds are working now, I will close this ticket.
qjackctl building for arm64 is kinda separate issue. but one I will be looking at today.

**Closed by falkTX** 2020-12-29 11:35 UTC

**Comment by robertchin** [comment] 2020-12-29 16:11
Looking for why the arm client can't connect to the x86_64 host.

**Comment by falkTX** [comment] 2020-12-29 16:44
it fails during `mmap` with "invalid argument"

**Comment by robertchin** [comment] 2020-12-30 11:03
I investigated the mmap issue further and it seems to be an OS issue since I can reproduce it with a separate simple test app. I will file a bug with Apple DTS.

**Comment by AndrewMorganMusic** [comment] 2024-04-29 17:05
https://forum.mod.audio/t/jack-audio-midi-on-macos/5018/2

**Comment by AndrewMorganMusic** [comment] 2024-04-29 17:06
https://www.youtube.com/watch?v=pnpYIGULBEQ
