### ISSUE TITLE
jack + alsa + flash = audio buffer underruns

### ISSUE THREAD

**Issue by comotion** [jackaudio/jack2#148] opened 2015-10-03 12:57 UTC
Hi,
Whenever I play audio from flash, ie on youtube, soundcloud etc, after a while, typically between 30s and 5 minutes, the audio becomes severely choppy. I have set up alsa to pipe everything to jack in .asoundrc.

    pcm.!default {
        type plug
        slave { 
           pcm "jack" 
        }
    }
    ctl.mixer0 {
        type hw
        card 1
    }
    pcm.jack {
        type jack
        name "alsa-jack"
        playback_ports {
            0 system:playback_5
            1 system:playback_6
        }
        capture_ports {
            0 system:capture_1
            1 system:capture_2
        }
    }

This is an easily reproducible problem, and I have tried many things to get rid of the choppines:
tweaking buffer sizes and piping through pulseaudio come to mind. 

I have an Echo AudioFire 4 and jack2 is my main audio driver, and I am running an up-to-date version of Arch Linux.

**Comment by nedko** [comment] 2016-03-07 13:07
There is no evidence that the choppy sound is caused by JACK itself. Thus I'm closing this issue.

**Closed by nedko** 2016-03-07 13:07 UTC

**Comment by multiburst** [comment] 2016-03-14 20:36
@comotion Hm, same problem here - you found any solution? 

In my case: was using pulseaudio -> jack, no issue. Then got rid of pulseaudio, everything works fine (even better!) - except sound in Firefox+Chromium. Sound is okay for maximum of 5 min., then I get choppy sound, regardless of buffer settings etc...soundcard is as well firewire, Presonus Firebox.

**Comment by comotion** [comment] 2016-03-16 13:42
Since it's an interaction between flash and jack/firewire, there was nowhere else to go.
@multiburst, I gave up and started using HTML5 instead of flash, which does not have this problem.

**Comment by multiburst** [comment] 2016-03-16 14:19
@comotion Hm...that's strange. I'm experiencing this behaviour with HTML5...which gets played through ffmpeg as far I know in Chrome/Firefox....

**Comment by byronsanchez** [comment] 2017-04-14 11:50
I'm having the exact same issue. If anyone found the cause and possibly a solution for this issue, I'd be sooo happy. I'll keep digging and try to report back if I find anything.

**Comment by unihedron** [comment] 2017-06-13 00:12
I had the same problem and I think it is now solved by installing **pulseaudio-module-jack**, and in qjackctl "Execute script after Startup" = **pactl set-default-sink jack_out**

Follow instructions on this page:
https://askubuntu.com/questions/572120/how-to-use-jack-and-pulseaudio-alsa-at-the-same-time-on-the-same-audio-device
