### ISSUE TITLE
can't check in named futex name = jack_sem.system

### ISSUE THREAD

**Issue by euwbah** [jackaudio/jack2#240] opened 2016-12-11 10:05 UTC
Jack2 seemed to have broken just yesterday. I have been getting this error:

```
Sun Dec 11 17:53:20 2016: ERROR: Allocate: can't check in named futex name = jack_sem.system err = Permission denied
Sun Dec 11 17:53:20 2016: ERROR: Cannot allocate synchro
Sun Dec 11 17:53:20 2016: ERROR: Cannot allocate internal client for driver
```

Here's the full log:
```
Sun Dec 11 18:05:05 2016: Starting jack server...
Sun Dec 11 18:05:05 2016: Jack: Server `default' registered
Sun Dec 11 18:05:05 2016: Jack: JackConnectionManager::InitConnections size = 19050752 
Sun Dec 11 18:05:05 2016: Jack: JackConnectionManager::InitClients
Sun Dec 11 18:05:05 2016: JACK server starting in realtime mode with priority 10
Sun Dec 11 18:05:05 2016: self-connect-mode is "Don't restrict self connect requests"
Sun Dec 11 18:05:05 2016: Jack: JackShmMem::new index = 0 attached = c240000 size = 107341338 
Sun Dec 11 18:05:05 2016: Jack: JackShmMem::new placement size = 38108698
Sun Dec 11 18:05:05 2016: Jack: Succeeded in locking 107341338 byte memory area
Sun Dec 11 18:05:05 2016: Jack: JackConnectionManager::InitConnections size = 19050752 
Sun Dec 11 18:05:05 2016: Jack: JackConnectionManager::InitClients
Sun Dec 11 18:05:05 2016: Jack: JackConnectionManager::InitConnections size = 19050752 
Sun Dec 11 18:05:05 2016: Jack: JackConnectionManager::InitClients
Sun Dec 11 18:05:05 2016: Jack: JackShmMem::new index = 1 attached = 1c071000 size = 1187 
Sun Dec 11 18:05:05 2016: Jack: Succeeded in locking 1187 byte memory area
Sun Dec 11 18:05:05 2016: Jack: JackPosixThread::StartImp : create non RT thread
Sun Dec 11 18:05:05 2016: Jack: JackPosixThread::ThreadHandler : start
Sun Dec 11 18:05:05 2016: Jack: playback device hw:PCH
Sun Dec 11 18:05:05 2016: Jack: capture device hw:PCH
Sun Dec 11 18:05:05 2016: Jack: capture device hw:PCH
Sun Dec 11 18:05:05 2016: Jack: playback device hw:PCH
Sun Dec 11 18:05:05 2016: Jack: apparent rate = 44100
Sun Dec 11 18:05:05 2016: Jack: frames per period = 1024
Sun Dec 11 18:05:05 2016: Jack: JackDriver::Open capture_driver_name = hw:PCH
Sun Dec 11 18:05:05 2016: Jack: JackDriver::Open playback_driver_name = hw:PCH
Sun Dec 11 18:05:05 2016: Jack: Check protocol client = 8 server = 8
Sun Dec 11 18:05:05 2016: Jack: JackEngine::ClientInternalOpen: name = system
Sun Dec 11 18:05:05 2016: Jack: JackEngine::AllocateRefNum ref = 0
Sun Dec 11 18:05:05 2016: Jack: JackLinuxFutex::Allocate name = jack_sem.system val = 0
Sun Dec 11 18:05:05 2016: ERROR: Allocate: can't check in named futex name = jack_sem.system err = Permission denied
Sun Dec 11 18:05:05 2016: ERROR: Cannot allocate synchro
Sun Dec 11 18:05:05 2016: ERROR: Cannot allocate internal client for driver
Sun Dec 11 18:05:05 2016: Jack: ~JackDriver
Sun Dec 11 18:05:05 2016: ERROR: Cannot initialize driver
Sun Dec 11 18:05:05 2016: Jack: no message buffer overruns
Sun Dec 11 18:05:05 2016: Jack: JackPosixThread::Stop
Sun Dec 11 18:05:05 2016: Jack: JackPosixThread::ThreadHandler : exit
Sun Dec 11 18:05:05 2016: ERROR: JackServer::Open failed with -1
Sun Dec 11 18:05:05 2016: Jack: Succeeded in unlocking 107341338 byte memory area
Sun Dec 11 18:05:05 2016: Jack: JackShmMem::delete size = 0 index = 0
Sun Dec 11 18:05:05 2016: Jack: ~JackDriver
Sun Dec 11 18:05:05 2016: Jack: Succeeded in unlocking 1187 byte memory area
Sun Dec 11 18:05:05 2016: Jack: JackShmMem::delete size = 0 index = 1
Sun Dec 11 18:05:05 2016: Jack: Cleaning up shared memory
Sun Dec 11 18:05:05 2016: Jack: Cleaning up files
Sun Dec 11 18:05:05 2016: Jack: Unregistering server `default'
Sun Dec 11 18:05:05 2016: ERROR: Failed to open server
```

**Comment by mseeber** [comment] 2016-12-11 10:55
`Sun Dec 11 18:05:05 2016: ERROR: Allocate: can't check in named futex name = jack_sem.system err = Permission denied`

Well, there we go.
I suspect, that an old entry of `jack_sem.system` already exists and can't be overwritten or a name collision is happening?

`ERROR: Allocate: can't check in named futex name` wait... futex? that PR is not even merged yet?

Please check which packet update broke that thing.

**Comment by mseeber** [comment] 2016-12-11 11:02
@falkTX could this be caused by someone merging #219 downstream?

**Comment by falkTX** [comment] 2016-12-11 11:19
I updated the jack2 kxstudio packages. just needs a JACK restart (or system one).

This is not a bug in the upstream jack2 code.

**Closed by falkTX** 2016-12-11 11:19 UTC
