### ISSUE TITLE
S24_LE not working for alsa driver

### ISSUE THREAD

**Issue by mr-berndt** [jackaudio/jack2#459] opened 2019-05-09 10:44 UTC
I understand that from jackd 1.9.11 on jack should be able to negotiate S24_LE with the card, if S32_LE is unavailable.

Now when I use a HAT on a Raspberry Pi which outputs SPDIF and can do S24_LE, like the Allo Digi One, this seems to fail:

Making sure the card can do it:
`# cat /proc/asound/card0/pcm0p/sub0/hw_params`
```
access: MMAP_INTERLEAVED
format: S24_LE
subformat: STD
channels: 2
rate: 192000 (192000/1)
period_size: 6960
buffer_size: 27840
```

Audio plays fine.

When starting jack with `jackd -R -P 50 -d alsa -P -r 96000 -p 8192 -n 3` I get:
```
creating alsa driver ... hw:0|-|8192|3|96000|0|0|nomon|swmeter|-|32bit
configuring for 96000Hz, period = 8192 frames (85.3 ms), buffer = 3 periods
ALSA: final selected sample format for playback: 24bit little-endian
```
and terribly noisy output (sounds like radio inbetween stations). When lowering the volume the sound becomes clear.

When starting jackd with `jackd -R -P 50 -d alsa -S -P -r 96000 -p 8192 -n 3`
I get
```
creating alsa driver ... hw:0|-|8192|3|96000|0|0|nomon|swmeter|-|16bit
configuring for 96000Hz, period = 8192 frames (85.3 ms), buffer = 3 periods
ALSA: final selected sample format for playback: 16bit little-endian
```
and the sound is fine but downconverted to 16 bits.

Is there some switch for S24_LE I am missing or is this a bug?

**Comment by 7890** [comment] 2019-05-09 14:04
Please try the most current git (master branch) and check if this is still an issue.
There was a related bug in the repository for a short period of time which is now fixed again. If you test it with current git, we can rule out any side-effects from that.

**Comment by mr-berndt** [comment] 2019-05-09 14:06
I used the latest commit from Apr. 27 - f7f2244b07ee0a723853e838de85e25471b8903f

**Comment by 7890** [comment] 2019-05-09 14:47
ok it's unrelated to the previous bug in that case.

**Comment by mr-berndt** [comment] 2019-05-20 16:16
Did you have a chance yet to look into it?

**Comment by 7890** [comment] 2019-05-20 21:12
What do you get with a simple `jackd --verbose -dalsa` ?
When jackd is running, `cat /proc/asound/card0/pcm0c/sub0/hw_params`

**Comment by romanticamaj** [comment] 2019-06-14 02:48
Hello, I have encountered the same issue with @mr-berndt with different environment

Environment:

- Linux imx6qsabresd 4.9.88-PgFx+ #92 SMP PREEMPT Wed May 22 14:01:41 CST 2019 armv7l armv7l armv7l GNU/Linux
- jack2 1.9.13
- imx6 flatform
- libasound.so.2.0.0

Test Result:

 - jackd -dalsa -p32 -Chw:0,1 -Phw:0,0    ->   has noise, check this file [float-32@24-bit@little-endian@48000Hz](https://drive.google.com/open?id=1442_mbN620q9TgS-MD9PFGDZ5KJra69d)

- jackd -dalsa -p32 -Chw:0,1 -Phw:0,0 -S   ->   has no noise, check this file [float-32@16-bit@little-endian@48000Hz](https://drive.google.com/open?id=1oBwArwHLc58qBAMTWN7V4XZfFAQ72O5A)

Can you help us to troubleshoot? Thanks!

------

this is the log of `jackd --verbose -dalsa -p32 -Chw:0,1 -Phw:0,0`

jackdmp 1.9.13
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2019 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
Jack: JackPosixThread::StartImp : create non RT thread
Jack: JackPosixThread::ThreadHandler : start
Jack: capture device hw:0,1
Jack: playback device hw:0,0
Jack: frames per period = 32
Jack: JackDriver::Open capture_driver_name = hw:0,1
Jack: JackDriver::Open playback_driver_name = hw:0,0
Jack: Check protocol client = 8 server = 8
Jack: JackEngine::ClientInternalOpen: name = system
Jack: JackEngine::AllocateRefNum ref = 0
Jack: JackLinuxFutex::Allocate name = jack_sem.0_default_system val = 0
Jack: JackEngine::NotifyAddClient: name = system
Jack: JackGraphManager::SetBufferSize size = 32
Jack: JackConnectionManager::DirectConnect first: ref1 = 0 ref2 = 0
Jack: JackGraphManager::ConnectRefNum cur_index = 0 ref1 = 0 ref2 = 0
Jack: JackDriver::SetupDriverSync driver sem in flush mode
creating alsa driver ... hw:0,0|hw:0,1|32|2|48000|0|0|nomon|swmeter|-|32bit
configuring for 48000Hz, period = 32 frames (0.7 ms), buffer = 2 periods
ALSA: final selected sample format for capture: 24bit little-endian
ALSA: use 2 periods for capture
ALSA: final selected sample format for playback: 24bit little-endian
ALSA: use 2 periods for playback
Jack: JackSocketServerChannel::Open
Jack: JackServerSocket::Bind : addr.sun_path /dev/shm/jack_default_0_0
Jack: JackSocketServerChannel::BuildPoolTable size = 1
Jack: JackEngine::Open
Jack: JackClientSocket::Connect : addr.sun_path /dev/shm/jack_default_0_0
Jack: JackEngine::ClientInternalOpen: name = freewheel
Jack: JackEngine::AllocateRefNum ref = 1
Jack: JackLinuxFutex::Allocate name = jack_sem.0_default_freewheel val = 0
Jack: JackEngine::NotifyAddClient: name = freewheel
Jack: JackDriver::ClientNotify ref = 1 driver = system name = freewheel notify = 0
Jack: JackDriver::ClientNotify ref = 0 driver = freewheel name = system notify = 0
Jack: JackConnectionManager::DirectConnect first: ref1 = 1 ref2 = 1
Jack: JackGraphManager::ConnectRefNum cur_index = 0 ref1 = 1 ref2 = 1
Jack: JackDriver::SetupDriverSync driver sem in flush mode
Jack: JackGraphManager::SetBufferSize size = 32
Jack: JackAlsaDriver::Attach fBufferSize 32 fSampleRate 48000
Jack: JackEngine::PortRegister ref = 0 name = system:capture_1 type = 32 bit float mono audio flags = 22 buffer_size = 32
Jack: JackGraphManager::AllocatePortAux port_index = 1 name = system:capture_1 type = 32 bit float mono audio
Jack: JackConnectionManager::AddOutputPort ref = 0 port = 1
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackAlsaDriver::Attach fCapturePortList[i] 1 
Jack: JackEngine::PortRegister ref = 0 name = system:capture_2 type = 32 bit float mono audio flags = 22 buffer_size = 32
Jack: JackGraphManager::AllocatePortAux port_index = 2 name = system:capture_2 type = 32 bit float mono audio
Jack: JackConnectionManager::AddOutputPort ref = 0 port = 2
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackAlsaDriver::Attach fCapturePortList[i] 2 
Jack: JackEngine::PortRegister ref = 0 name = system:capture_3 type = 32 bit float mono audio flags = 22 buffer_size = 32
Jack: JackGraphManager::AllocatePortAux port_index = 3 name = system:capture_3 type = 32 bit float mono audio
Jack: JackConnectionManager::AddOutputPort ref = 0 port = 3
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackAlsaDriver::Attach fCapturePortList[i] 3 
Jack: JackEngine::PortRegister ref = 0 name = system:capture_4 type = 32 bit float mono audio flags = 22 buffer_size = 32
Jack: JackGraphManager::AllocatePortAux port_index = 4 name = system:capture_4 type = 32 bit float mono audio
Jack: JackConnectionManager::AddOutputPort ref = 0 port = 4
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackAlsaDriver::Attach fCapturePortList[i] 4 
Jack: JackEngine::PortRegister ref = 0 name = system:capture_5 type = 32 bit float mono audio flags = 22 buffer_size = 32
Jack: JackGraphManager::AllocatePortAux port_index = 5 name = system:capture_5 type = 32 bit float mono audio
Jack: JackConnectionManager::AddOutputPort ref = 0 port = 5
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackAlsaDriver::Attach fCapturePortList[i] 5 
Jack: JackEngine::PortRegister ref = 0 name = system:capture_6 type = 32 bit float mono audio flags = 22 buffer_size = 32
Jack: JackGraphManager::AllocatePortAux port_index = 6 name = system:capture_6 type = 32 bit float mono audio
Jack: JackConnectionManager::AddOutputPort ref = 0 port = 6
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackAlsaDriver::Attach fCapturePortList[i] 6 
Jack: JackEngine::PortRegister ref = 0 name = system:capture_7 type = 32 bit float mono audio flags = 22 buffer_size = 32
Jack: JackGraphManager::AllocatePortAux port_index = 7 name = system:capture_7 type = 32 bit float mono audio
Jack: JackConnectionManager::AddOutputPort ref = 0 port = 7
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackAlsaDriver::Attach fCapturePortList[i] 7 
Jack: JackEngine::PortRegister ref = 0 name = system:capture_8 type = 32 bit float mono audio flags = 22 buffer_size = 32
Jack: JackGraphManager::AllocatePortAux port_index = 8 name = system:capture_8 type = 32 bit float mono audio
Jack: JackConnectionManager::AddOutputPort ref = 0 port = 8
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackAlsaDriver::Attach fCapturePortList[i] 8 
Jack: JackEngine::PortRegister ref = 0 name = system:playback_1 type = 32 bit float mono audio flags = 21 buffer_size = 32
Jack: JackGraphManager::AllocatePortAux port_index = 9 name = system:playback_1 type = 32 bit float mono audio
Jack: JackConnectionManager::AddInputPort ref = 0 port = 9
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackAlsaDriver::Attach fPlaybackPortList[i] 9 
Jack: JackEngine::PortRegister ref = 0 name = system:playback_2 type = 32 bit float mono audio flags = 21 buffer_size = 32
Jack: JackGraphManager::AllocatePortAux port_index = 10 name = system:playback_2 type = 32 bit float mono audio
Jack: JackConnectionManager::AddInputPort ref = 0 port = 10
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackAlsaDriver::Attach fPlaybackPortList[i] 10 
Jack: JackEngine::PortRegister ref = 0 name = system:playback_3 type = 32 bit float mono audio flags = 21 buffer_size = 32
Jack: JackGraphManager::AllocatePortAux port_index = 11 name = system:playback_3 type = 32 bit float mono audio
Jack: JackConnectionManager::AddInputPort ref = 0 port = 11
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackAlsaDriver::Attach fPlaybackPortList[i] 11 
Jack: JackEngine::PortRegister ref = 0 name = system:playback_4 type = 32 bit float mono audio flags = 21 buffer_size = 32
Jack: JackGraphManager::AllocatePortAux port_index = 12 name = system:playback_4 type = 32 bit float mono audio
Jack: JackConnectionManager::AddInputPort ref = 0 port = 12
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackAlsaDriver::Attach fPlaybackPortList[i] 12 
Jack: JackEngine::PortRegister ref = 0 name = system:playback_5 type = 32 bit float mono audio flags = 21 buffer_size = 32
Jack: JackGraphManager::AllocatePortAux port_index = 13 name = system:playback_5 type = 32 bit float mono audio
Jack: JackConnectionManager::AddInputPort ref = 0 port = 13
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackAlsaDriver::Attach fPlaybackPortList[i] 13 
Jack: JackEngine::PortRegister ref = 0 name = system:playback_6 type = 32 bit float mono audio flags = 21 buffer_size = 32
Jack: JackGraphManager::AllocatePortAux port_index = 14 name = system:playback_6 type = 32 bit float mono audio
Jack: JackConnectionManager::AddInputPort ref = 0 port = 14
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackAlsaDriver::Attach fPlaybackPortList[i] 14 
Jack: JackEngine::PortRegister ref = 0 name = system:playback_7 type = 32 bit float mono audio flags = 21 buffer_size = 32
Jack: JackGraphManager::AllocatePortAux port_index = 15 name = system:playback_7 type = 32 bit float mono audio
Jack: JackConnectionManager::AddInputPort ref = 0 port = 15
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackAlsaDriver::Attach fPlaybackPortList[i] 15 
Jack: JackEngine::PortRegister ref = 0 name = system:playback_8 type = 32 bit float mono audio flags = 21 buffer_size = 32
Jack: JackGraphManager::AllocatePortAux port_index = 16 name = system:playback_8 type = 32 bit float mono audio
Jack: JackConnectionManager::AddInputPort ref = 0 port = 16
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackEngine::ClientNotify: no callback for notification = 9
Jack: JackAlsaDriver::Attach fPlaybackPortList[i] 16 
Jack: Clock source : system clock via clock_gettime
Jack: JackServer::Start
Jack: JackThreadedDriver::Start
Jack: JackPosixThread::StartImp : create non RT thread
Jack: JackPosixThread::ThreadHandler : start
Jack: JackThreadedDriver::Init real-time
Jack: JackPosixThread::AcquireRealTimeImp priority = 10
Jack: JackPosixThread::StartImp : create non RT thread
Jack: JackPosixThread::ThreadHandler : start
Jack: JackSocketServerChannel::ClientCreate socket
Jack: JackSocketServerChannel::BuildPoolTable size = 2
Jack: JackSocketServerChannel::BuildPoolTable fSocketTable i = 1 fd = 14
Jack: JackSocketServerChannel::Execute : fPollTable i = 1 fd = 14
Jack: JackRequest::Notification
Jack: JackDriver::ClientNotify ref = 1 driver = freewheel name = freewheel notify = 18
Jack: JackDriver::ClientNotify ref = 1 driver = freewheel name = freewheel notify = 18
Jack: JackDriver::ClientNotify ref = 1 driver = freewheel name = freewheel notify = 18
Jack: JackDriver::ClientNotify ref = 1 driver = freewheel name = freewheel notify = 18
Jack: JackEngine::ClientNotify: no callback for notification = 4
Jack: JackEngine::ClientNotify: no callback for notification = 4

`cat /proc/asound/card0/pcm1c/sub0/hw_params `
access: MMAP_INTERLEAVED
format: S24_LE
subformat: STD
channels: 8
rate: 48000 (48000/1)
period_size: 32
buffer_size: 64

**Comment by romanticamaj** [comment] 2019-06-14 05:58
Furthermore,

this issue looks the same to this faq "[MacBook running Linux: audio via JACK is distorted, audio via ALSA is not](http://jackaudio.org/faq/macbook_distortion.html)"

although the platform is not the same, the issue can be reproduced on my platform.

**Comment by mr-berndt** [comment] 2019-06-14 09:39
Oh, I missed the notice of 7890's answer a couple of weeks back, so I didn't reply. Sorry.
I am away over the weekend but will generate a log next week as well, so we can compare. It would be really good, if we got this fixed.

**Comment by romanticamaj** [comment] 2019-06-15 07:44
Should we reconsider these commits`c5a0f5ea...831163e5^`?

According to alsa spec S24_LE "Signed 24 bit Little Endian using **low** three bytes in 32-bit word"

On master and develop branch, this conversion is removed. Is that right for ALSA?

**Comment by romanticamaj** [comment] 2019-06-17 02:36
After I make these commits `c5a0f5ea...831163e5` back
(by `git revert 05bc08c64e9747ae7e9db75b9f667564d3784380`, issue #426 )

the noise under S24_LE is gone.

Can anyone help us to check? Thanks!

**Comment by 7890** [comment] 2019-06-17 16:05
In PR from @twischer-adit 
https://patch-diff.githubusercontent.com/raw/jackaudio/jack2/pull/397.diff
Some of the changes introduced a special sort of clipping for certain types of drivers. However other parts seemed reasonable, I'm sure you could find related sources there for the initial problem described.

**Comment by twischer-adit** [comment] 2019-06-25 11:09
@romanticamaj 
> According to alsa spec S24_LE "Signed 24 bit Little Endian using low three bytes in 32-bit word"

Yes. This was exactly the reason for my patch set.

@7890 
> Some of the changes introduced a special sort of clipping for certain types of drivers

With my patch set 1.0f will also be represented in S32 as 0x7FFFFFFF. Therefore any number above 1.0f would result in an overflow/clipping. Without my patch set it is 0x7FFFFF00. Therefore there is some head room for values >1.0f. But I think my proposal would be more accurate because the loudness would not change when switching between S32 and S16.

Anyway may be we could keep the old S32 conversion and use my new S24 conversion. (Unfortunately I am currently busy with other tasks)

**Comment by mr-berndt** [comment] 2019-06-26 18:35
Sorry, I was too busy myself but it seems, my input is no longer needed to see the issue?

**Comment by romanticamaj** [comment] 2019-06-27 16:10
I think you can try this on master or develop branch:

`git revert 05bc08c64e9747ae7e9db75b9f667564d3784380`

then, install the built jack2 lib and try to reproduce the issue again.

If the issue is not reproducible, I think the root cause is the way of S24_LE - float conversion that I mentioned earlier.

Let us know the result. It will be great.

**Comment by mr-berndt** [comment] 2019-06-30 08:19
OK, will do and report back. Thx.

**Comment by mr-berndt** [comment] 2019-06-30 08:27
Another hint here, pointing to the need of S24_4LE for all cards, which actually report S24_LE as needed format.

https://github.com/balbuze/volumio-plugins/issues/210

**Comment by flo-at** [comment] 2020-05-07 15:00
I can confirm the problem using the current Raspbian release.

**Closed** 2021-10-01 11:37 UTC
