### ISSUE TITLE
undefined symbol: jackctl_driver_get_type

### ISSUE THREAD

**Issue by Chris-Barton** [jackaudio/jack2#159] opened 2015-11-14 15:33 UTC
Ok so ill get all of the spec stuff out the way first

Raspberry PI B+
Running this image: http://docs.emlid.com/Downloads/Real-time-Linux-RPi1/#sd-card-image
Compiled git Master version using scripts as in Readme

any time I try to use jackd i get this error:

$sudo jackd -R -S -P59 -d oss

jackdmp 1.9.11
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2015 Grame.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
jackd: symbol lookup error: jackd: undefined symbol: jackctl_driver_get_type

Ive tried a number of different example but all end with the symbol lookup error

I realise this is not likely to be a a problem with jack more likely my set-up and im sorry if this has already been asked but if anyone has any advice id really appreciate it.

Regards Chris

**Comment by lilrc** [comment] 2015-12-13 20:05
Hmm. Maybe you could post a build log. I request the output of
```
./waf configure
./waf -vv --jobs=1
./waf install
```
or whatever you use to build and install. I guess the linker warns about this at compile time.

**Comment by nedko** [comment] 2016-03-07 13:04
This is probably caused by multiple installs. There is no feedback since at all. Thus I'm closing this issue.

**Closed by nedko** 2016-03-07 13:04 UTC
