### ISSUE TITLE
jack_client_close makes jackd session unstable on macOS 12.1

### ISSUE THREAD

**Issue by gisogrimm** [jackaudio/jack2#841] opened 2022-01-25 11:32 UTC
When `jack_client_close()` is called then jackd becomes unstable. Terminating clients without calling `jack_client_close()` works as expected.

## Environment

* **JACK Version:** 1.9.20
* **Operating System:** macOS 12.1 on Mac mini (M1, 2020)
* **Installation:** Installer from jackaudio.org

Using Jack 1.9.19 installed via brew the behavior is the same, only the error messages are different. Before the update to macOS 12.1 it worked fine.

## Steps To Reproduce

minimal client:

```
#include <jack/jack.h>

int main(int argc,char**argv)
{
  jack_client_t* jc;
  jack_status_t stat;
  jc = jack_client_open("test",0,&stat);
  if( jc )
    jack_client_close( jc );
  return 0;
}
```
To reproduce, compile, start `jackd -d dummy` and the minimal client (same with coreaudio backend).

The server output is:

```
% jackd -d dummy          
jackdmp 1.9.20
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2021 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
JackMachSemaphore::Destroy failed to kill semaphore server thread...
JackMachSemaphoreServer::Execute: receive error - 268451846:(ipc/rcv) port changed
```

The client output:

```
% ./test_close
Cannot read socket fd = 9 err = Socket is not connected
CheckRes error
JackSocketClientChannel read fail
```
In a more complex application with multiple clients per process this resulted in a segmentation fault when accessing any other client after one client called `jack_client_close()`.

**Comment by gisogrimm** [comment] 2022-01-25 19:53
Probably the same problem as in #822

**Comment by gisogrimm** [comment] 2022-01-26 19:47
For further analysis of this problem I created a tiny repository:
[https://github.com/gisogrimm/test_jack_client_close](https://github.com/gisogrimm/test_jack_client_close)
On macOS 12.1 I get this output:
```
% ./test_jack_client_close
0.017392 jack_client_open succeeded
0.030845 jack_activate(jc1) returned 0
1.056131 jack_client_open succeeded
1.076925 jack_activate(jc2) returned 0
2.081963 port type is "32 bit float mono audio"
3.101637 jack_deactivate(jc1) returned 0
Cannot read socket fd = 9 err = Socket is not connected
CheckRes error
JackSocketClientChannel read fail
4.125995 jc1 is shutting down.
4.126036 jack_client_close(jc1) returned 0
5.131068 port type jc2 is "32 bit float mono audio"
Server is not running
6.136175 jack_deactivate(jc2) returned -1
Server is not running
Cannot read socket fd = 11 err = Bad file descriptor
CheckRes error
JackSocketClientChannel read fail
7.141355 jc2 is shutting down.
7.156431 jack_client_close(jc2) returned -1
8.194136 jack_client_open succeeded
9.199156 port type is "32 bit float mono audio"
Cannot read socket fd = 9 err = Socket is not connected
CheckRes error
JackSocketClientChannel read fail
10.227126 jc1 is shutting down.
10.243492 jack_client_close returned 0
```
Sometimes I get a segmentation fault after the first `jack_client_close()`. On Ubuntu 20.04 (system-installed jackd version 1.9.12):
```
> ./test_jack_client_close 
0.022922 jack_client_open succeeded
0.041031 jack_activate(jc1) returned 0
1.065289 jack_client_open succeeded
1.086365 jack_activate(jc2) returned 0
2.086525 port type is "32 bit float mono audio"
3.090819 jack_deactivate(jc1) returned 0
4.093537 jack_client_close(jc1) returned 0
5.093697 port type jc2 is "32 bit float mono audio"
6.098823 jack_deactivate(jc2) returned 0
7.109120 jack_client_close(jc2) returned 0
8.129467 jack_client_open succeeded
9.129623 port type is "32 bit float mono audio"
10.159834 jack_client_close returned 0
```
This is closer to what I would expect.

**Comment by gisogrimm** [comment] 2022-01-27 07:26
The test code here
https://github.com/gisogrimm/test_jack_client_close/tree/e80b69401b75676bbf597d9982eb1862dcbf2dee
reproducibly results in a segmentation fault, output is provided in the README.md of that repo. The main difference to a prior version with only error messages, but only occasional segfaults, was the addition of process callbacks.

**Comment by vrslev** [comment] 2022-02-24 20:48
> Probably the same problem as in https://github.com/jackaudio/jack2/issues/822

@gisogrimm For me semaphore errors started showing after version 1.9.20 (https://github.com/jackaudio/jack2/pull/788). Other stuff always was there on 1.9.19.

@p--b @falkTX Any comments?

**Comment by gisogrimm** [comment] 2022-02-24 21:05
Just for the record: Compiling the clients for Intel (e.g., using github actions) does not show this problem, those clients work well with the arm64 jack server. This is the workaround I am currently applying to run jack clients (and most specifically processes with multiple clients and corresponding jack_client_close calls).

**Comment by p--b** [comment] 2022-02-24 22:13
Interesting. Definitely looks like something isn't right here but I don't have access to M1 hardware to experiment, sadly.
The output from the server is concerning;

```
JackMachSemaphore::Destroy failed to kill semaphore server thread...
```

Hmm, why? We'll come back to this question later. However, _even if_ this kill fails, we still `delete` the instance, which I'm guessing is a bad idea if the thread is actually running - maybe this is responsible for the segfaults?
(https://github.com/jackaudio/jack2/blob/develop/macosx/JackMachSemaphore.mm#L372)

```
JackMachSemaphoreServer::Execute: receive error - 268451846:(ipc/rcv) port changed
```

This is an interesting clue. That error string implies that `mach_msg` (https://github.com/jackaudio/jack2/blob/develop/macosx/JackMachSemaphoreServer.mm#L45) returned this:

```
 MACH_RCV_PORT_CHANGED
    receive_name specified a receive right which was moved into a port set during the call. 
```
(https://web.mit.edu/darwin/src/modules/xnu/osfmk/man/mach_msg.html)

Here, `receive_name` is `fServerReceive`, which is allocated and released by `JackMachSemaphore`, where it is `fServicePort`. Interestingly, this is released after the thread is "killed" (or not, as the case may be...). Well, perhaps what's happening is not that the receive right was "moved into a port set", but that it was straight up destroyed (by us - https://github.com/jackaudio/jack2/blob/develop/macosx/JackMachSemaphore.mm#L381)

What's interesting is that in this failure case we `return true` from `Execute()` and continue processing, still using the same receive port - even though we've potentially released it. This seems bad, especially if IDs are reused...

So, my first guess was that it all goes wrong because the kill fails. I don't understand why this would not happen on M1 but not Intel/Rosetta2. Let's look at why `Kill()` would give us `< 0` back:
https://github.com/jackaudio/jack2/blob/develop/posix/JackPosixThread.cpp#L160

Ah, the thread was never started? That seems odd, seeing as the very first thing we do after creating it is to start it?
```
    fThreadSemServer = new JackMachThread(fSemServer);

    if (fThreadSemServer->Start() < 0) {
```
Or maybe it was already `Kill()`ed? Either way the thread ought not to be running - but yet we see the port changed error printed _after_ the kill "fails". So that is rather strange.

An alternative way that fServicePort could get used after being deallocated is if `JackMachSemaphore::Disconnect()` was called for some reason on the server side (https://github.com/jackaudio/jack2/blob/develop/macosx/JackMachSemaphore.mm#L336) - that function is intending to decrement the client's ref count for that port send right, but would on the server result in our one client reference (for the receive right) being decremented and the port going away.

*Maybe a useful next step here would be to get the verbose output of jackd in the original repro (that showed the failed to kill / receive error outputs), so we have a more complete picture of what exactly is occurring?*

**Comment by gisogrimm** [comment] 2022-02-25 13:27
Please find attached the verbose jackd stdout (jack.out.txt) and stderr (jack.err.txt) as well as the output of the test program. This time it did not crash, still the behaviour was not clean (server shutdown message on first client close). It was a fresh install of jack universal (1.9.20) from jackaudio.org. I can look into more detail next week.

[jack.out.txt](https://github.com/jackaudio/jack2/files/8141480/jack.out.txt)
[jack.err.txt](https://github.com/jackaudio/jack2/files/8141481/jack.err.txt)
[test.out.txt](https://github.com/jackaudio/jack2/files/8141484/test.out.txt)
[test.err.txt](https://github.com/jackaudio/jack2/files/8141486/test.err.txt)

**Comment by HaHeho** [comment] 2022-03-01 19:26
I am having problems with `jack_client_close()` as well, but on
- JACK Version: 1.9.20
- Operating System: macOS 12.2.1 on **MacBook Pro (Intel)**
- Installation: "jack2-macOS-intel-v1.9.20.tar.gz" from https://github.com/jackaudio/jack2-releases/releases

Symptoms are instantiating, activating and closing a few clients in a Python loop. Closing them yields an error message and segfault.
```
Cannot read socket fd = 15 err = Socket is not connected
CheckRes error
JackSocketClientChannel read fail

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
``` 

Something must broke there (not just on M1 hardware).

I did not run any of the test scripts you suggested above. Let me know if it would help.

I will go back to earlier versions of the pre-build installers and see if it happens there as well.

**Comment by skyflyer** [comment] 2022-04-04 21:35
Same here, both M1 and Intel macs - been using rust bindings, but reproduced with minimal repro from @gisogrimm in C as well (compiled simply with `gcc -ljack test_client.c`).

Currently using jackd 1.9.20.... and I've just restarted the machine (I know! :)) (jackd wouldn't start with weird errors before, I'm assuming something to do with broken semaphore and IPC on Mac...).

The rust program reliably segfaults _every_ time. The C program just fails when finishing. My error is a bit different though (FWIW):

```
Cannot read socket fd = 9 err = Socket is not connected
CheckRes error
JackSocketClientChannel read fail
```

I'm attaching a `dtruss` (strace equivalent?) output if anyone has an idea of what's happening - the dtruss invocation of "simple client" "hangs"...

<details><summary>dtruss output</summary>

```
❯ sudo dtruss ./a.out
dtrace: system integrity protection is on, some features will not be available

SYSCALL(args) 		 = return
access("/AppleInternal/XBS/.isChrooted\0", 0x0, 0x0)		 = -1 2
bsdthread_register(0x7FF801230000, 0x7FF80122FFEC, 0x2000)		 = 1073742303 0
shm_open(0x7FF8010FEF5D, 0x0, 0x10FD7BA)		 = 3 0
fstat64(0x3, 0x7FF7BB53C0E0, 0x0)		 = 0 0
mmap(0x0, 0x2000, 0x1, 0x40001, 0x3, 0x0)		 = 0x104AC7000 0
close(0x3)		 = 0 0
ioctl(0x2, 0x4004667A, 0x7FF7BB53C194)		 = 0 0
mprotect(0x104ACE000, 0x1000, 0x0)		 = 0 0
mprotect(0x104AD3000, 0x1000, 0x0)		 = 0 0
mprotect(0x104AD4000, 0x1000, 0x0)		 = 0 0
mprotect(0x104AD9000, 0x1000, 0x0)		 = 0 0
mprotect(0x104AC9000, 0x90, 0x1)		 = 0 0
mprotect(0x104AC9000, 0x90, 0x3)		 = 0 0
mprotect(0x104AC9000, 0x90, 0x1)		 = 0 0
mprotect(0x104ADA000, 0x1000, 0x1)		 = 0 0
mprotect(0x104ADB000, 0x90, 0x1)		 = 0 0
mprotect(0x104ADB000, 0x90, 0x3)		 = 0 0
mprotect(0x104ADB000, 0x90, 0x1)		 = 0 0
mprotect(0x104AC9000, 0x90, 0x3)		 = 0 0
mprotect(0x104AC9000, 0x90, 0x1)		 = 0 0
mprotect(0x104ADA000, 0x1000, 0x3)		 = 0 0
mprotect(0x104ADA000, 0x1000, 0x1)		 = 0 0
issetugid(0x0, 0x0, 0x0)		 = 0 0
getentropy(0x7FF7BB53B2F0, 0x20, 0x0)		 = 0 0
getentropy(0x7FF7BB53B350, 0x40, 0x0)		 = 0 0
getpid(0x0, 0x0, 0x0)		 = 23896 0
stat64("/AppleInternal\0", 0x7FF7BB53C6B0, 0x0)		 = -1 2
csops_audittoken(0x5D58, 0x7, 0x7FF7BB53C1E0)		 = -1 22
proc_info(0x2, 0x5D58, 0xD)		 = 64 0
csops_audittoken(0x5D58, 0x7, 0x7FF7BB53C2D0)		 = -1 22
sysctlbyname(kern.osvariant_status, 0x15, 0x7FF7BB53C700, 0x7FF7BB53C6F8, 0x0)		 = 0 0
csops(0x5D58, 0x0, 0x7FF7BB53C734)		 = 0 0
sysctlbyname(kern.system_version_compat, 0x1A, 0x0, 0x0, 0x7FF7BB53C764)		 = 0 0
geteuid(0x0, 0x0, 0x0)		 = 0 0
getuid(0x0, 0x0, 0x0)		 = 0 0
dtrace: error on enabled probe ID 1717 (ID 572: syscall::sysctl:return): invalid kernel access in action #10 at DIF offset 28
gettid(0x7FF7BB53A9A0, 0x7FF7BB53A9A4, 0x0)		 = -1 3
geteuid(0x0, 0x0, 0x0)		 = 0 0
getegid(0x0, 0x0, 0x0)		 = 0 0
csops(0x5D58, 0x0, 0x7FF7BB53B6EC)		 = 0 0
gettid(0x7FF7BB53A970, 0x7FF7BB53A974, 0x0)		 = -1 3
geteuid(0x0, 0x0, 0x0)		 = 0 0
getegid(0x0, 0x0, 0x0)		 = 0 0
csrctl(0x0, 0x7FF7BB53B95C, 0x4)		 = -1 1
mprotect(0x1049C5000, 0x100000, 0x1)		 = 0 0
bsdthread_create(0x104C24B40, 0x7F871101C218, 0x700007F54000)		 = 133513216 0
thread_selfid(0x0, 0x0, 0x0)		 = 373902 0
__semwait_signal(0x903, 0x0, 0x1)		 = -1 60
dtrace: error on enabled probe ID 1717 (ID 572: syscall::sysctl:return): invalid kernel access in action #10 at DIF offset 28
geteuid(0x0, 0x0, 0x0)		 = 0 0
mkdir("/tmp/jack_db-0\0", 0x1F8, 0x0)		 = -1 17
getrlimit(0x1008, 0x7FF7BB53DA30, 0x0)		 = 0 0
open_nocancel("/tmp/jack_db-0/DB_CONFIG\0", 0x0, 0x0)		 = -1 2
stat64("/var/tmp\0", 0x7FF7BB53D830, 0x0)		 = 0 0
open("/tmp/jack_db-0/__db.001\0", 0xA02, 0x1B0)		 = -1 17
open("/tmp/jack_db-0/__db.001\0", 0x2, 0x0)		 = 3 0
fcntl(0x3, 0x1, 0x13)		 = 0 0
fcntl(0x3, 0x2, 0x1)		 = 0 0
fstat64(0x3, 0x7FF7BB53DE78, 0x0)		 = 0 0
dtrace: error on enabled probe ID 1689 (ID 174: syscall::read:return): invalid kernel access in action #12 at DIF offset 68
lseek(0x3, 0x1D8, 0x0)		 = 472 0
dtrace: error on enabled probe ID 1689 (ID 174: syscall::read:return): invalid kernel access in action #12 at DIF offset 68
close(0x3)		 = 0 0
open("/tmp/jack_db-0/__db.001\0", 0x2, 0x0)		 = 3 0
fcntl(0x3, 0x1, 0x13)		 = 0 0
fcntl(0x3, 0x2, 0x1)		 = 0 0
mmap(0x0, 0x102000, 0x3, 0x40201, 0x3, 0x0)		 = 0x104AE3000 0
dtrace: error on enabled probe ID 1717 (ID 572: syscall::sysctl:return): invalid kernel access in action #10 at DIF offset 28
open("/tmp/jack_db-0/__db.002\0", 0x202, 0x1B0)		 = 4 0
fcntl(0x4, 0x1, 0x13)		 = 0 0
fcntl(0x4, 0x2, 0x1)		 = 0 0
mmap(0x0, 0x16000, 0x3, 0x40201, 0x4, 0x0)		 = 0x104BE5000 0
open("/tmp/jack_db-0/__db.003\0", 0x202, 0x1B0)		 = 5 0
fcntl(0x5, 0x1, 0x13)		 = 0 0
fcntl(0x5, 0x2, 0x1)		 = 0 0
mmap(0x0, 0x42000, 0x3, 0x40201, 0x5, 0x0)		 = 0x104D59000 0
geteuid(0x0, 0x0, 0x0)		 = 0 0
stat64("/tmp/jack_db-0/metadata.db\0", 0x7FF7BB53DC60, 0x0)		 = 0 0
open("/tmp/jack_db-0/metadata.db\0", 0x2, 0x0)		 = 6 0
fcntl(0x6, 0x1, 0x13)		 = 0 0
fcntl(0x6, 0x2, 0x1)		 = 0 0
dtrace: error on enabled probe ID 1689 (ID 174: syscall::read:return): invalid kernel access in action #12 at DIF offset 68
close(0x6)		 = 0 0
open("/tmp/jack_db-0/metadata.db\0", 0x202, 0x0)		 = 6 0
fcntl(0x6, 0x1, 0x13)		 = 0 0
fcntl(0x6, 0x2, 0x1)		 = 0 0
fstat64(0x6, 0x7FF7BB53DDD8, 0x0)		 = 0 0
sigprocmask(0x1, 0x7FF7BB53E64C, 0x7F8711012030)		 = 0x0 0
socket(0x1, 0x1, 0x0)		 = 7 0
geteuid(0x0, 0x0, 0x0)		 = 0 0
connect(0x7, 0x7FF7BB53E300, 0x6A)		 = 0 0
setsockopt(0x7, 0xFFFF, 0x1022)		 = 0 0
shutdown(0x7, 0x2, 0x0)		 = 0 0
close(0x7)		 = 0 0
__semwait_signal(0x903, 0x0, 0x1)		 = -1 60
socket(0x1, 0x1, 0x0)		 = 7 0
geteuid(0x0, 0x0, 0x0)		 = 0 0
connect(0x7, 0x7FF7BB53E3D0, 0x6A)		 = 0 0
setsockopt(0x7, 0xFFFF, 0x1022)		 = 0 0
dtrace: error on enabled probe ID 1687 (ID 176: syscall::write:return): invalid kernel access in action #12 at DIF offset 68
dtrace: error on enabled probe ID 1687 (ID 176: syscall::write:return): invalid kernel access in action #12 at DIF offset 68
dtrace: error on enabled probe ID 1687 (ID 176: syscall::write:return): invalid kernel access in action #12 at DIF offset 68
dtrace: error on enabled probe ID 1687 (ID 176: syscall::write:return): invalid kernel access in action #12 at DIF offset 68
dtrace: error on enabled probe ID 1687 (ID 176: syscall::write:return): invalid kernel access in action #12 at DIF offset 68
dtrace: error on enabled probe ID 1687 (ID 176: syscall::write:return): invalid kernel access in action #12 at DIF offset 68
dtrace: error on enabled probe ID 1687 (ID 176: syscall::write:return): invalid kernel access in action #12 at DIF offset 68

^C
read(0x7, "\0", 0x4)		 = -1 4
```
</details>

**Closed** 2022-04-15 19:03 UTC
Labels: bug

**Comment by skyflyer** [comment] 2022-04-19 11:19
Thank you 🙏! I can confirm it works now without issues.

**Comment by falkTX** [comment] 2022-04-19 11:36
For those interested, the issue was that `thread_terminate` has changed behavior on macOS 12.
I do not have links or extra info as to why or how, but it just does. This is something jack2 relies on, so a few things suddenly stopped working.

I took the chance to cleanup/rework the macOS semaphore stuff a bit too, so it doesnt rely on thread termination. But the socket code in jack2 heavily relies on it, would be quite a substantial rework (that applies to all OSes) to get that working on a similar fashion (cleaning closing a thread instead of terminating/killing it).
So now macOS uses the posix APIs as fallback for thread termination, instead of the macOS specific ones (that no longer work).

If you see any more similar issues, please report them.

**Comment by p--b** [comment] 2022-04-19 15:53
Thanks very much for this, I did intend to look into this further but never had the time 👍

**Comment by gisogrimm** [comment] 2022-04-19 16:00
Thanks a lot, this is very good news!
