### ISSUE TITLE
Linking error with readline (waf-macosx-fixes branch)

### ISSUE THREAD

**Issue by joshdekock** [jackaudio/jack2#180] opened 2015-12-20 18:51 UTC
```
18:49:19 runner ['/usr/bin/clang', 'example-clients/transport.c.28.o', '-o', '/Users/ethe/jack2/build/example-clients/jack_transport', '-Lcommon', '-ljack', '-lpthread', '-lreadline']
Undefined symbols for architecture x86_64:
  "_whitespace", referenced from:
      _stripwhite in transport.c.28.o
      _execute_command in transport.c.28.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
May be related to the waf issues currently?

**Comment by lilrc** [comment] 2015-12-20 18:57
I don't think so; this is new. I will look into this when I get time!

**Comment by joshdekock** [comment] 2015-12-20 19:24
Looking into it, readline has the whitespace() function, as a macro, which happens to be exactly the same as the one already provided.
```diff
diff --git a/example-clients/transport.c b/example-clients/transport.c
index 4847c1b..58ac241 100644
--- a/example-clients/transport.c
+++ b/example-clients/transport.c
@@ -31,7 +31,7 @@
 #include <jack/jack.h>
 #include <jack/transport.h>

-#ifndef HAVE_READLINE
+#ifndef whitespace
 #define whitespace(c) (((c) == ' ') || ((c) == '\t'))
 #endif
```
This patch fixes it: if readline's macro is found it will default to that, else it will define the non-readline macro (which still works if readline is being used)

**Comment by lilrc** [comment] 2015-12-29 19:40
This code should not be triggered since whitespace is only defined if HAVE_READLINE is not defined, which it must be since you are compiling with readline (so HAVE_READLINE=1). Something is wrong... Please paste your build log.

**Comment by joshdekock** [comment] 2016-01-14 19:58
@lilrc https://gist.github.com/anonymous/1708d5e49efd0d78edbb

**Comment by KimJeongYeon** [comment] 2016-01-28 06:24
I made a better patch:
 1) jack_transport fixed linking issue.
 2) fixed build warning.

```diff
diff --git a/example-clients/transport.c b/example-clients/transport.c
index 4847c1b..5ce6ab6 100644
--- a/example-clients/transport.c
+++ b/example-clients/transport.c
@@ -24,14 +24,14 @@
 #include <signal.h>
 #include <stdlib.h>
 #include <string.h>
-#ifdef HAVE_READLINE
+#if HAVE_READLINE
 #include <readline/readline.h>
 #include <readline/history.h>
 #endif
 #include <jack/jack.h>
 #include <jack/transport.h>
 
-#ifndef HAVE_READLINE
+#if !HAVE_READLINE
 #define whitespace(c) (((c) == ' ') || ((c) == '\t'))
 #endif
 
@@ -353,14 +353,15 @@ static char *stripwhite(char *string)
      
 	return s;
 }
-     
+
+#if HAVE_READLINE
 static char *dupstr(char *s)
 {
 	char *r = malloc(strlen(s) + 1);
 	strcpy(r, s);
 	return r;
 }
-     
+
 /* Readline generator function for command completion. */
 static char *command_generator (const char *text, int state)
 {
@@ -386,10 +387,11 @@ static char *command_generator (const char *text, int state)
      
 	return (char *) NULL;		/* No names matched. */
 }
+#endif
 
 static void command_loop()
 {
-#ifdef HAVE_READLINE
+#if HAVE_READLINE
 	char *line, *cmd;
 	char prompt[32];
 
@@ -408,7 +410,7 @@ static void command_loop()
 	/* Read and execute commands until the user quits. */
 	while (!done) {
 
-#ifdef HAVE_READLINE
+#if HAVE_READLINE
 		line = readline(prompt);
      
 		if (line == NULL) {	/* EOF? */
@@ -418,8 +420,12 @@ static void command_loop()
 		}
 #else
 		printf("%s> ", package);
-		fgets(line, sizeof(line), stdin);
-		line[strlen(line)-1] = '\0';
+		if (!fgets(line, sizeof(line), stdin)) {
+			done = 1;
+			break;
+		} else {
+			line[strlen(line)-1] = '\0';
+		}
 #endif
      
 		/* Remove leading and trailing whitespace from the line. */
@@ -428,13 +434,13 @@ static void command_loop()
 		/* If anything left, add to history and execute it. */
 		if (*cmd)
 		{
-#ifdef HAVE_READLINE
+#if HAVE_READLINE
 			add_history(cmd);
 #endif
 			execute_command(cmd);
 		}
      
-#ifdef HAVE_READLINE
+#if HAVE_READLINE
 		free(line);		/* realine() called malloc() */
 #endif
 	}
```

**Comment by lilrc** [comment] 2016-01-28 09:51
@KimJeongYeon, can you post a full build log (the output of ./waf configure && ./waf -vv) and the contents of build/config.h? I am curious to see if HAVE_READLINE is defined somehow and why this is triggered on MacOSX and not Linux...

**Comment by lilrc** [comment] 2016-01-28 09:52
Oh, it should be ./waf -vv -j1

**Comment by lilrc** [comment] 2016-01-28 10:09
Oh, I see it. It sure is defined. However, I do not understand why the transport program is built if readline is not properly found. `example-clients/wscript:39` reads
```
conf.env['BUILD_EXAMPLE_CLIENT_TRANSPORT'] = conf.env['READLINE']
```
so somehow READLINE = True... Please also post the content of `build/c4che/_cache.py`.

**Comment by lilrc** [comment] 2016-01-28 10:33
@KimJeongYeon, I pushed variations of your changes as dd7d234 and a907931.

**Comment by joshdekock** [comment] 2016-02-24 23:25
We need to merge the fixes for this into waf-macosx-fixes, this is the only thing blocking #190

**Comment by lilrc** [comment] 2016-02-25 17:51
@joshdekock, master is merged into waf-macosx-fixes. What do we need to do to resolve this? Can you reproduce this? Can you post a full build log?

@KimJeongYeon, ping.

**Comment by joshdekock** [comment] 2016-02-25 18:18
@lilrc here's the current build log https://gist.github.com/joshdekock/cc71fe9d9eccc61c2139
Regarding what we need to do, I'm gonna take another look at it, see if I can make a quick patch, however the real problem is that the whole build system needs to be revised, it's become very messy.

**Comment by joshdekock** [comment] 2016-02-25 18:35
@lilrc maybe you could come on irc for a little bit while we solve this quickly, but I think it's something to do with the fact that OSX's readline doesn't have `whitespace()`. I checked the headers /usr/include/readline/*.h and none of them defined it.

**Closed** 2016-02-25 19:42 UTC
