### ISSUE TITLE
jack2-dbus cannot allocate memory

### ISSUE THREAD

**Issue by miquecg** [jackaudio/jack2#429] opened 2019-02-12 19:19 UTC
Every time I start jack server (`jack2-dbus`) with Cadence I see this in the logs:

```
Tue Feb 12 19:29:16 2019: JACK server starting in realtime mode with priority 90
Tue Feb 12 19:29:16 2019: self-connect-mode is "Don't restrict self connect requests"
Tue Feb 12 19:29:16 2019: ERROR: Cannot lock down 82280346 byte memory area (Cannot allocate memory)
```

I've followed [this guide](http://jackaudio.org/faq/linux_rt_config.html) in order to allow jack to run with realtime scheduling. According to the logs it's indeed like this but something must be going wrong with memory limits, thus the message.

For the record, my user limits are these:

```
➜ % ~  ulimit -a                            
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         unlimited
-m: resident set size (kbytes)      unlimited
-u: processes                       30774
-n: file descriptors                1024
-l: locked-in-memory size (kbytes)  unlimited
-v: address space (kbytes)          unlimited
-x: file locks                      unlimited
-i: pending signals                 30774
-q: bytes in POSIX msg queues       819200
-e: max nice                        0
-r: max rt priority                 98
-N 15:                              unlimited
```

**Comment by dvzrv** [comment] 2019-02-12 22:09
Does this also happen if you start `jackd` from the terminal (do not use gnome terminal!)?

**Comment by miquecg** [comment] 2019-02-13 10:28
Apparently `jack2-dbus` doesn't come with `jackd` binary. I should try with `jackdbus` instead:

```
➜ % ~  which jackd
jackd not found
➜ % ~  which jackdbus
/usr/bin/jackdbus
➜ % ~  jackdbus --help
jackdbus should be auto-executed by D-Bus message bus daemon.
If you want to run it manually anyway, specify "auto" as only parameter
```

That's how Cadence deals with the server, using dbbus.

```
➜ % ~  ps aux | grep jack
      3204  0.1  0.0  29972  7444 ?        Ss   11:18   0:00 /usr/bin/jackdbus auto
```

This is having Cadence started but server not running.

**Comment by dvzrv** [comment] 2019-02-13 11:36
Which desktop environment are you using?
Did you log out and in again after adding yourself to the realtime group?

You can interchangably use (that is to install) the jack2 or jack2-dbus package (the separation was introduced due to a matter of preference over how to start jack): `pacman -S jack2` (after which you can start using `jackd`).
Only the default activation method changes (the jack2-dbus package only provides dbus activation, but doesn't bring the jackd way of starting jack). Note: Cadence might not work properly with the jack2 package, therefore read on and for the sake of reproducibility start jack in a minimal way:

With jack2-dbus you will want to use `jack_control` to start/stop/modify jack (check `jack_control --help`).
With jack2 you will want to use the `jackd` executable (check `man 1 jackd`).

**Comment by miquecg** [comment] 2019-02-13 12:28
> Which desktop environment are you using?

Gnome.

> Did you log out and in again after adding yourself to the realtime group?

Yes.

`jack_control start` produces the same error message in the logs.

**Comment by dvzrv** [comment] 2019-02-15 00:16
After a little more probing, I think this might be related to [a bug in systemd 240](https://github.com/systemd/systemd/issues/11386) and should be [fixed with 241](https://github.com/systemd/systemd/pull/11448).
Let's wait and see...

**Comment by dvzrv** [comment] 2019-02-20 21:29
I've just tested this with systemd 241 and the issue is gone. `MEMLOCK` set through limits.conf once again properly propagates throughout the `user@.service` (and thus also a user's `dbus.service`, etc.).
I think we can safely classify this as "not our bug" and put the systemd tag on it. ;-)
I just really hope for users of non-rolling release distros, that they won't get stuck on systemd 240.
Also: This can be closed!

**Closed** 2019-02-20 23:16 UTC
Labels: dbus

**Comment by falkTX** [comment] 2019-02-21 09:29
Thanks for the investigation and testing!

**Comment by miquecg** [comment] 2019-02-21 12:34
I can also confirm that this issue is finally gone. Thanks for debugging!
