### ISSUE TITLE
Windows 10 - JACK-Router ASIO not seen MAX/MSP

### ISSUE THREAD

**Issue by Polkjia** [jackaudio/jack2#699] opened 2021-01-06 17:25 UTC
Hello,

I installed Jack2 on my windows 10 machine to route audio from and to Max/MSP and SuperCollider. I tried first with max, and the JACK-Router ASIO just does not appear. What might be the problem?

**Comment by falkTX** [comment] 2021-01-06 18:04
Please try with https://github.com/jackaudio/jack2-releases/releases/tag/untagged-dc253c3f5ca380ada300 builds
jack-router is not included in the 1.9.16 in the current downloads.

let us know if that works for you

**Comment by Polkjia** [comment] 2021-01-06 18:32
First of all thank you very much, now I can see the driver, but when I turn on Max audio, something starts to beep badly and this appears on console 


![Screenshot (351)](https://user-images.githubusercontent.com/77069555/103806869-e9ce8480-5055-11eb-94d7-8ea61ba7d0a6.png)


Overflow of some kind?

**Comment by falkTX** [comment] 2021-01-06 18:38
yikes, that qjackctl scaling looks rough.

this seems like an xrun.
stop the jack server, increase buffer size in the settings and start it again. (changing buffer size when jack is running seems to be broken at the moment)

**Comment by Polkjia** [comment] 2021-01-06 18:43
Definitely a XRun.

![Screenshot (352)](https://user-images.githubusercontent.com/77069555/103807668-1040ef80-5057-11eb-99c7-8b894c213ebc.png)


64 and 128 samples do not let me start the server, while the picture above was with 512 samples. Idk how Jack works, but it seems strange, I have a pretty powerful laptop (i7 9750H) under my fingers.  I can easily run at 128 I/O and signal vector size on Max.

**Comment by falkTX** [comment] 2021-01-06 19:32
It depends on the drivers.
JACK on windows is using portaudio, which does not always work well. ASIO devices are recommended, not sure if that is the case here.

There is an idea of changing that backend to something that is known to work better, but that has not happened yet.

**Comment by Polkjia** [comment] 2021-01-06 20:19
Hello,

thank you for the help. I was able to make it work even at 16 samples by defining the server Prefix as follow 
`jackd -R -S -d portaudio`
thanks to a user on the facebook unofficial max msp forum (he basically sent me a pic of his settings and I tried my luck). My default was
`jackd -S -X winmme`
but anyway, it looks it is working (even tho it sounds as there is... more latency then 16 samples. I am now using headphones from laptop mini-jack, so it might have something to do with).

Btw, I tried to compile the .iss files in other older releases, to get the .exe to install them. It says to me that INNO compiler wasn't able to find the version.iss file.

> There is an idea of changing that backend to something that is known to work better, but that has not happened yet.

I would love to help, but unfortunately I have not the required skills. I suggest to put the file you posted for me as windows download tho, it would probably avoid a day of head scratching to other windows users.

**Comment by falkTX** [comment] 2021-01-06 22:05
> Hello,
> 
> thank you for the help. I was able to make it work even at 16 samples by defining the server Prefix as follow
> `jackd -R -S -d portaudio`
> thanks to a user on the facebook unofficial max msp forum (he basically sent me a pic of his settings and I tried my luck). My default was
> `jackd -S -X winmme`
> but anyway, it looks it is working (even tho it sounds as there is... more latency then 16 samples. I am now using headphones from laptop mini-jack, so it might have something to do with).

This `-d portaudio` should not be there, and might be the reason why latency ends up not being what you expect.

Regarding building jack2, that was changed somewhat recently.
It is handled now in https://github.com/jackaudio/jack2-releases
Windows builds are created on a linux machine through mingw cross-compiler. 
(they are automated through travis CI, so if you read the CI files you should be able to deploy a similar setup and reproduce the build in a way)

Anyway, since it seems you solved your issue, I am closing the ticket

**Closed by falkTX** 2021-01-06 22:05 UTC
