### ISSUE TITLE
Jack2 audio engine shuts down when mapping a Midi controller.

### ISSUE THREAD

**Issue by Olnium** [jackaudio/jack2#931] opened 2023-04-29 18:32 UTC
I'm having an issue where if I try to map my Midi controller, the audio engine shuts down continuously. QjackCtl itself remains running and I'm able to restart the engine, but as soon as I attempt to map a control, it shuts down again.

## Environment

* **JACK Version:**

jackdmp version 1.9.22 tmpdir server protocol 9

Bitwig Studio 4.4.10
Novation Nocturn Midi Controller using Automap driver version 4.12
NI Traktor 3 LE

* **Operating System:**

Edition	Windows 11 Pro
Version	22H2
OS build	22621.1635
Experience	Windows Feature Experience Pack 1000.22641.1000.0

* **Hardware Platform**

AMD Ryzen 5600G at stock speeds, Gigabyte B550m Aorus Elite, 16 Gb Crucial RAM.
Presonus Studio 26c USB C Audio Interface. Driver version: 5.28.0.18152

* **Installation:**

Installed with Windows binary.

## Steps To Reproduce

1. Start QjackCtl
2. Start Bitwig Studio
3. Start Traktor
4. Attempt to map a controller knob in either program
5. Jack2 audio engine shuts down
6. Restart engine
7. GoTo step 4

### Expected vs. actual behavior

Expected: Jack2 is able to run and route audio between 2 applications which are controlled with hardware Midi controllers.

Actual: Jack 2 audio engine repeatedly shuts down when attempting to map a Midi controller to either of the 2 applications.

Edit: this appears to be happening whenever I send any midi data between devices/applications over loopMIDI virtual midi cable. This definitely didn't occur with the previous version.

**Comment by ericjessee** [comment] 2023-05-04 17:33
I'm having a potentially related problem when trying to route MIDI from Pro Tools to another application. All seems fine, but as soon as I press a key on the MIDI controller the jack engine shuts down inexplicably.
Have you tried an older version of jack? with release 1.9.15 it works normally, but I get the shutdowns when using 1.9.22. Have not tried other versions.

**Comment by Olnium** [comment] 2023-05-04 18:40
> I'm having a potentially related problem when trying to route MIDI from Pro Tools to another application. All seems fine, but as soon as I press a key on the MIDI controller the jack engine shuts down inexplicably. Have you tried an older version of jack? with release 1.9.15 it works normally, but I get the shutdowns when using 1.9.22. Have not tried other versions.

Same for me with v 1.9.22. Everything is able to be routed, but as soon as there's a stream of midi data, the engine crashes. I've rolled back to 1.9.21 and everything works as expected.

**Comment by ReinholdH** [comment] 2023-05-05 02:57
On Windows Jack 1.9.22 immediately crashes when a MIDI event is received from an external MIDI device. 
Jack 1.9.21 works fine. 

Please see the verbose dump of Jack 1.9.22 here
[Jack_1.9.22_verbose_dump_when_MIDI_keyboard_is_connected.txt.zip](https://github.com/jackaudio/jack2/files/11402966/Jack_1.9.22_verbose_dump_when_MIDI_keyboard_is_connected.txt.zip)

To me there is something fundamentally broken in Jack 1.9.22

**Comment by falkTX** [comment] 2023-10-29 08:16
Fixed in 0d730dd3567f250edaa899af906b8a8593e3492f, to be part of next release.
Also the issue was always there since the start on win64 builds, was fine on win32

**Closed as completed by falkTX** 2023-10-29 08:16 UTC
Labels: bug

**Comment by TallGirlVanessa** [comment] 2024-04-06 05:08
I can confirm that installing the nightly fixes the issue for me. For me the issue was triggered when telling Ableton Live to send MIDI syncs for VCV Rack, in case that helps anyone Googling.
