### ISSUE TITLE
Jack does not support 32 bit mode in ALSA

### ISSUE THREAD

**Issue by claudiocabral** [jackaudio/jack2#810] opened 2021-11-12 10:37 UTC
Jack always assumes only 24 out of 32 bits are used in its ALSA driver, even if the sample format is 32_LE.

Previously this only caused a dynamic range reduction, but with the latest fixes to 24 bit handling in alsa (see #459 and #798 ), 32 bit cards suffer a gain reduction of 48dB in their outputs and clip very early in their inputs.

Reproduced both on Aarch64 and x86_64, both with linux, using builds from commit 0727bbc386288f6ff5cb6876d2321836d562221e
used a behringer UMC404HD sound card to test on x86_64

**Comment by takaswie** [comment] 2021-12-13 13:30
Hi,

I'm ALSA upstream committer.

A few days ago my patch was merged into kernel prepatch for v5.17 (future release).
The patch just adds comment into UAPI of ALSA PCM interface, and might be a
supplemental information to the issue.

 * https://git.kernel.org/pub/scm/linux/kernel/git/tiwai/sound.git/commit/?id=fb6723daf89083a0d2290f3a0abc777e40766c84

In short, when ALSA driver reports `[S|U]32` format of audio sample, it's better for
userspace application to evaluate `msbits` hardware parameter. It expresses the number
of available bits in MSB side of the audio sample. The alsa-lib has API,
`snd_pcm_hw_params_get_sbits()`, for the purpose.

For example, the hardware transfers 24 bit `left-justified` or `right-padding` audio sample
in 32 bit slot, the `msbits` hardware parameter results in `24`. In the case, the audio
sample is like:

```
(MSB) oooooooo oooooooo oooooooo xxxxxxxx(LSB)
```

so that `o` sign is for available bit, but `x` sign should be invalidated by application.

When the hardware transfers 32 bit audio sample in 32 bit slot, the `msbits` hardware
parameter results in `32`, thus no bit should be invalidated.

At present, jackd implementation looks to support the first example, but no care for the second
example.

I note that `[S|U]24` of ALSA PCM format is for `right-justified` or `left-padding` audio
sample, thus:

```
(MSB) xxxxxxxx oooooooo oooooooo oooooooo(LSB)
```

Regards

**Comment by claudiocabral** [comment] 2021-12-13 15:31
Hi @takaswie, thanks for your input.

That is indeed the case, but not only does jack not care about the 32 `msbits`, it pretends that i's 24 `msbits`,
resulting in a gain reduction of ~48bits (dividing the signal by 256).
the PR #811 that I made adds support for 32 `msbits`

**Comment by takaswie** [comment] 2021-12-13 23:57
Hi @claudiocabral  (also mention to @falkTX , @rncbc ),

> Hi @takaswie, thanks for your input.
> 
> That is indeed the case, but not only does jack not care about the 32 `msbits`, it pretends that it's 24 `msbits`, resulting in a gain reduction of ~48dBs (dividing the signal by 256). the PR #811 that I made adds support for 32 `msbits`

No. Your patch brings regression to some drivers; e.g. snd-ice1712, snd-ice1724, snd-hdsp, snd-rme9652, snd-ua101, and so on, since it doesn't check `msbits` hardware parameter to distinguish the cases.

In short, for the case of little endian format, LSB 0 numbering:

 * SNDRV_PCM_FORMAT_[S|U]32_LE
     * msbits = 32
         * (MSB) oooooooo oooooooo oooooooo oooooooo (LSB) 
     * msbits = 24
         * (MSB) oooooooo oooooooo oooooooo xxxxxxxx (LSB) 
  * SNDRV_PCM_FORMAT_[S|U]24_LE
      * (MSB) xxxxxxxx oooooooo oooooooo oooooooo (LSB) 
  * SNDRV_PCM_FORMAT_[S|U]24_3LE
      * (MSB) oooooooo oooooooo oooooooo (LSB) 

so that 'x' should be invalidated. Unless evaluation of value from `snd_pcm_hw_params_get_sbits()`, userspace application cannot handle the case of `SNDRV_PCM_FORMAT_[S|U]32_LE` correctly.

Historically, the issue (24 bit sample in 32 bit frame, upper bits are available, lower bits should be invalidated) is long-standing in jackd. Many developer manages to fix it but brought regression each time. For example, in #426, patches are reverted by @rncbc .

I'm afraid that you follow to the human nature of history repeats.

**Comment by claudiocabral** [comment] 2021-12-14 02:53
Now I get, hadn't read your original comment thoroughly enough.
Don't intend to follow the human nature of repeating history, will add the fixes tomorrow :)
Thanks a lot for this heads up

**Comment by claudiocabral** [comment] 2021-12-14 12:47
@takaswie , could you this commit 5726150e2c51b37f949b717fbd2cd9660ca92e35?
Does it address this issue? I don't have hardware here to test it

**Comment by takaswie** [comment] 2021-12-15 02:20
Hi @claudiocabral,

At first I apologize that I pointed out the regression in your patch. The
regression has already been included. It came from the commit 0727bbc38628
("ALSA: convert properly S24_LE"). We already face the history repeats...

> * SNDRV_PCM_FORMAT_[S|U]32_LE
>       
>       * msbits = 32 (upper 32 bits are available in 32 bit slot)
>         
>         * (MSB) oooooooo oooooooo oooooooo oooooooo (LSB)
>       * msbits = 24 (upper 24 bits are available in 32 bit slot)
>         
>         * (MSB) oooooooo oooooooo oooooooo xxxxxxxx (LSB)
> 
>     * SNDRV_PCM_FORMAT_[S|U]24_LE (lower 24 bits are available in 32 bit slot)
>       
>       * (MSB) xxxxxxxx oooooooo oooooooo oooooooo (LSB)
> 
>     * SNDRV_PCM_FORMAT_[S|U]24_3LE
>       
>       * (MSB) oooooooo oooooooo oooooooo (LSB)

As long as I investigate in kernel space, current status as of 0727bbc38628 is:

| sample format | msbits | state | description                                |
| ------------- | ------ | ----- | ------------------------------------------ |
| S32_LE        |     32 | NG    | 32 bit sample in 32 bit slot               |
| S32_LE        |     24 | NG    | 24 bit sample at upper side in 32 bit slot |
| S24_[L\|B]E   |      - | OK    | 24 bit sample at lower side in 32 bit slot |
| S24_3[L\|B]E  |      - | OK    | 24 bit sample in 24 bit slot               |

as @claudiocabral said, therefore his work should be categorized into two parts:

 * fix the regression for [S|U]32_[L|B]E format
 * distinguish available bit count correctly

I evaluate with below commits accumulated over the issued commit (0727bbc38628):

* 94d9c6f5 apply changes without whitespace
* b0b0c5ee remove neon intrinsics and fix indentation
* e5a46a47 update float_32 macro and fix misspellings
* 5726150e check msbits to determine number of bits in alsa driver

As a result, the status becomes better:

| sample format | msbits | state | description                                |
| ------------- | ------ | ----- | ------------------------------------------ |
| S32_LE        |     32 | OK    | 32 bit sample in 32 bit slot               |
| S32_LE        |     24 | OK    | 24 bit sample at upper side in 32 bit slot |
| S24_[L\|B]E   |      - | OK    | 24 bit sample at lower side in 32 bit slot |
| S24_3[L\|B]E  |      - | OK    | 24 bit sample in 24 bit slot               |

I have some nitpicking to his patchset:

1. Exception handling. The snd-cd4281 and snd-intel8x0 uses 20 bits
   sample at upper side in 32 bit slot, thus msbits is 20. For the case,
   it's better to exit program.

2. BE support. We can see SND_PCM_FORMAT_S32_BE in 'formats' local variable
   in 'alsa_driver_configure_stream()' function. It's better to support it.

3. Message output. Users are probably puzzled when 32 bit slot is selected
but 24 bit sample is processed internally. It's friendly to output the
message.

Thanks

**Comment by claudiocabral** [comment] 2021-12-17 20:10
Hi, I'll look into adding the better messages and exception handling in the next couple of weeks,
I won't be able to look into code a lot the next couple of days.
I suggest BE support should com in a future PR just to keep this one concise

**Comment by claudiocabral** [comment] 2022-01-04 14:47
@takaswie , I'm back to work and I believe I have addressed your concerns.
Please let me know what you think of it when you get time.
I ended up adding BE support, as it seems that all the functions are capable of handling it.
That said, I haven't tested, as I don't have any BE devices.

**Closed** 2022-01-15 15:02 UTC
Labels: bug
