### ISSUE TITLE
Relyable delayed connection

### ISSUE THREAD

**Issue by keinstein** [jackaudio/jack2#403] opened 2018-12-19 10:20 UTC
Hi,
I'm mainaining a fork of RtMidi (https://github.com/keinstein/rtmidi/) that allows reliable MIDI connections and to seprarate the configuration and connection steps. There ist at least one piece of software that connects to the MIDI devices (https://github.com/keinstein/rtmidi/) an arbitrary amount of time after the configuration. This is necessary as Windows and ALSA offer exclusive access to MIDI ports so the application should be disconnected when it is not active. For various reasons it must provide a limited patch panel for MIDI and other music connections internally. This would be too complex for a completely interactive mode.

What is the best way to achieve this goal in JACK? Port names seem not to be reliable as there is such a function as jack_port_rename which may hit the user between configuration and activation of the MIDI subsystem.

Currently I use jack_port_t* as main port descriptor. But then I have the problem that I  JACK doesn't support to connect two ports referenced by jack_port_t*. As names may change I'd like to avoid names at all. So what is the right way to implement this?
By port descriptor I mean some data that MUST not change in that sense that a later connection request leads to the same network as if it would have been if the ports get connected immediately.  I would be fine with a UUID, but all UUIDs I get are zero.

A related question is: How to compare two instances of jack_port_t? I suppose comparing the pointers is not enough. Currently I compare port type and name. Does this work reliable over the whole session? Even after renaming ports? I mean I have a jack_port_t pointer a, then the port gets renamed. I obtain another jack_port_t pointer (by accident or somehow over jack_get_ports) of the same port. Does jack_port_name return the same string on both instances?

**Comment by falkTX** [comment] 2018-12-19 11:58
"Delayed connection" as you suggest is not possible within JACK design.
Ports can come and go at any point in time. Though if you are only worried about port renames, you can listen to port rename callbacks to keep things in sync within your application.
Note that port names are how you uniquely identify ports, so comparing 2 ports can be done by simply comparing their name (no need to compare type as well).
Holding to jack_port_t pointers (of ports that are not your own) is not a good idea. You cannot rename ports that do not belong to you. 
UUID (meta-data) was not implemented in JACK2 until recently

**Comment by keinstein** [comment] 2018-12-20 12:51
It's not about me renaming the ports.

Listening to port renames adds a lot of additional complexity to my code. Currently my library returns a list of port descriptors (for JACK mainly jack_port_t pointers) to the user program. As I already said these references are managed by smart pointers, so my library does not care about them until they get destroyed or used to open a port.

This means I would have add extra complexity to my library in order to manage an extra centralized string database that is updated on every port name change. Currently, I don't see any chance in doing so without adding an additional race conditions during the process of port renaming as I can't lock the database between starting the renaming by another client and the notification and between the notification of my client and the notification of my client and the end of the notification process.

I'm aware that ports can come and go at any point in time. Even just after calling jack_get_port_by_name before doing some other queries. So JACK must always check the validity of any jack_port_t *  and return a proper result if the port has disappeared.

BTW: If I'm not mistaken jack_port_t* is just an alias of jack_port_id_t. Otherwise jack_port_by_id and jack_port_by_name should contain information about how and when the structure is freed.

**Comment by 7890** [comment] 2019-01-20 19:45
I'm sorry the problem is not very clear (to me), if there is a question, please re-open or use corresponding mailing list. Changing the port semantics in a way described is out of scope for now. The thread is still archived for later reference, thanks for your input!

**Closed by 7890** 2019-01-20 19:45 UTC
